### ISSUE TITLE
Hardcoded IP

### ISSUE THREAD

**Issue by kevinpapst** [AliGeenius/Kimai-RFID-ESP#4]
Today I was browsing the code, trying to understand it and stumbled upon:

https://github.com/AliGeenius/Kimai-RFID-ESP/blob/2fa1927fa584e69efc880bc658654f4005fa036b/src/main.cpp#L114

Is that on purpose or a mistake where the config should be used instead?

**Comment by AliGeenius** [comment]
Hi @kevinpapst 
that's truely a bug! Wondering that nobody reported problems :smiling_face_with_tear: 
thanks for your report and good eyes!
Will be fixed
